### ISSUE TITLE
Please add eventemitter3-timer along side with pixi-timer

### ISSUE THREAD

**Issue by soimy** [cursedcoder/awesome-pixijs#4]
Since [pixi-timer](https://github.com/Nazariglez/pixi-timer) is not active and not working with pixi v4.5+, I've written a new plugin with almost the same API interface named [eventemitter3-timer](https://github.com/soimy/eventemitter3-timer) with typescript support.

Sample codes: https://jsfiddle.net/ygs4zfLj/

Please add to let more people reach it, thanks!

**Comment by cursedcoder** [comment]
Added, thanks!
